name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      run: |
        git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
        cd $HOME/gotip/src
        ./make.bash
        echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
        echo "$HOME/gotip/bin:$PATH" >> $GITHUB_PATH

    - name: Test
      run: go test ./... -race -coverprofile=coverage.out

    - name: Upload Coverage
      uses: codecov/codecov-action@v2
      with:
        files: coverage.out

    